sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
env:
  global:
  - secure: OGymTwGxIFRhkUdU4o3NaEWRh+HkzQXy4TlHROj/ZPxmX67ptAgPwNxIrotckNzQuzHZPWNeTdrzqvBcyOAtvqyBA/MzDTTIHRs5KOqsyxge09H/x3wODGjdDmmwZ9eOLKERwtdDdx/3g8iTwjslLOMOGtCzmXlBWBlZ/r2cZMtrXUwkOR5gBxAiqTyOaEILJ1iQxSrJG2oZftuQaUKs1akbPDGRVKrB1rmx1lDJYtAFlB5lihqcFwlunr998PueGziGeHx9ars/7TULFvCNKf0UIQ9cT2FUPc9Ua/TnNLedAn4XPV2UpjrIBPIyNDah4gEv7v0GJoptJ6umc9NUdZLjkdBuunQrtjpyw6gvSMjarK/BT/IcLKMRuQXNGWLAGupe9TJu0VBu6mJK3ov9Btkya6NjQUa5OfDt6PrJTakqkDpR0Xz6EJVZv6FdRs/lXMZhH1lODL2I6qq18TUulbc7ZfexOLE/n+8vfrzG+xxr0dSnem6T1JmXuonelYWj5XcGEsnYpDsaMOoJzLOLeeaivOmvEVp1Q3aHXFRKC2iwuepqrpW8bR/rGpRPTqiNmD1uaj7MKq0Dlkz7P4tygstv5zDOw6Ef26z81wqNm/j2vkPscV3mL7nK2vTtpoXqBgtl5YR5QyHHK+esS/YWW5zxaOF5LTc91obqiDjtcck=
  - secure: LayNm8w86mtAwrHSsWtwQkH6FWtgzUEoc6dETTFYSFEGIjvZoI+IDKuOXJQY+l6JGshbEhyYMmWbwujp17iIwGtxJkg0UZTDEqu24o+UvnygmSYXMulEnbX/DVUeZ/oN1bqLiQY3euqVKIFD35kG84l4p40Dl2FM4s4hEpztW5FC2vOOjTu3aj17Lwvky76qZgWj1Vfi83F2ZLeXM9dqFo7ZMwFzK2uukyzWnNa5fXPIMEIQ8fo7/ZdkiQ9+C+fy35wEy6PIpN03Bjoe+VOoNL//fM+I00Ua2u3ObcqJWrD514Y7pssccRl5Zne4PUnCwWxMtwlfdsyU5z59tzE9qygRZKUItmYeabjaxt1dtAY2MprBl2gaBjwkSG+ZzgOs4jfOHUiDMxE/8R+QSCTPF6koyfvN0iBglPye3tkGtUiLUeztdQph+m+rwkTB2FOVHH29wD7C1DfMwx1D1HdOkV+OZExbtubU3QD9rCzzGgtv77zL8PhbDZ2GKdUedywBVvHMGtqy4GMHNd+qedH5NfTM1VKS3Et3Qqh9NwiYC2S4LlzE3iw0MJREcSqo8f4WhNdJE/n8IJzJxhHpRuxlOahmRXCcuz6x3uIHKSnEa5mLBzf9KDDTFXVvWt+e1L5iI15UZ8JfyTE5E12LwNrdUa2zN517rS5UAenLoY5I7Tw=
